// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nflvjqxchdhdodpnknvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mbHZqcXhjaGRoZG9kcG5rbnZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwMzQ5NjAsImV4cCI6MjA4NjYxMDk2MH0.d8gI3So5IJ50mfQ4VSsKatGdlJSeVwH4foLwVEPshOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});